#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/install-nginx
- name: Mettre à jour le cache apt
  ansible.builtin.apt:
    update_cache: yes

- name: Installer Nginx
  apt:
    name: nginx
    state: present

- name: Démarrer Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Copier une page web pour les 3 machines
  copy:
    content: "{{ html_content }}"
    dest: /var/www/html/index.html
